/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  Bitrix24Integration as PrismaBitrix24Integration,
} from "@prisma/client";

export class Bitrix24IntegrationServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.Bitrix24IntegrationCountArgs, "select">
  ): Promise<number> {
    return this.prisma.bitrix24Integration.count(args);
  }

  async bitrix24Integrations(
    args: Prisma.Bitrix24IntegrationFindManyArgs
  ): Promise<PrismaBitrix24Integration[]> {
    return this.prisma.bitrix24Integration.findMany(args);
  }
  async bitrix24Integration(
    args: Prisma.Bitrix24IntegrationFindUniqueArgs
  ): Promise<PrismaBitrix24Integration | null> {
    return this.prisma.bitrix24Integration.findUnique(args);
  }
  async createBitrix24Integration(
    args: Prisma.Bitrix24IntegrationCreateArgs
  ): Promise<PrismaBitrix24Integration> {
    return this.prisma.bitrix24Integration.create(args);
  }
  async updateBitrix24Integration(
    args: Prisma.Bitrix24IntegrationUpdateArgs
  ): Promise<PrismaBitrix24Integration> {
    return this.prisma.bitrix24Integration.update(args);
  }
  async deleteBitrix24Integration(
    args: Prisma.Bitrix24IntegrationDeleteArgs
  ): Promise<PrismaBitrix24Integration> {
    return this.prisma.bitrix24Integration.delete(args);
  }
}
