/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Bitrix24IntegrationWhereInput } from "./Bitrix24IntegrationWhereInput";
import { Type } from "class-transformer";

@ArgsType()
class Bitrix24IntegrationCountArgs {
  @ApiProperty({
    required: false,
    type: () => Bitrix24IntegrationWhereInput,
  })
  @Field(() => Bitrix24IntegrationWhereInput, { nullable: true })
  @Type(() => Bitrix24IntegrationWhereInput)
  where?: Bitrix24IntegrationWhereInput;
}

export { Bitrix24IntegrationCountArgs as Bitrix24IntegrationCountArgs };
