/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Bitrix24IntegrationWhereInput } from "./Bitrix24IntegrationWhereInput";
import { IsOptional, ValidateNested, IsInt } from "class-validator";
import { Type } from "class-transformer";
import { Bitrix24IntegrationOrderByInput } from "./Bitrix24IntegrationOrderByInput";

@ArgsType()
class Bitrix24IntegrationFindManyArgs {
  @ApiProperty({
    required: false,
    type: () => Bitrix24IntegrationWhereInput,
  })
  @IsOptional()
  @ValidateNested()
  @Field(() => Bitrix24IntegrationWhereInput, { nullable: true })
  @Type(() => Bitrix24IntegrationWhereInput)
  where?: Bitrix24IntegrationWhereInput;

  @ApiProperty({
    required: false,
    type: [Bitrix24IntegrationOrderByInput],
  })
  @IsOptional()
  @ValidateNested({ each: true })
  @Field(() => [Bitrix24IntegrationOrderByInput], { nullable: true })
  @Type(() => Bitrix24IntegrationOrderByInput)
  orderBy?: Array<Bitrix24IntegrationOrderByInput>;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { Bitrix24IntegrationFindManyArgs as Bitrix24IntegrationFindManyArgs };
