/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Bitrix24IntegrationCreateInput } from "./Bitrix24IntegrationCreateInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";

@ArgsType()
class CreateBitrix24IntegrationArgs {
  @ApiProperty({
    required: true,
    type: () => Bitrix24IntegrationCreateInput,
  })
  @ValidateNested()
  @Type(() => Bitrix24IntegrationCreateInput)
  @Field(() => Bitrix24IntegrationCreateInput, { nullable: false })
  data!: Bitrix24IntegrationCreateInput;
}

export { CreateBitrix24IntegrationArgs as CreateBitrix24IntegrationArgs };
