/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Bitrix24IntegrationWhereUniqueInput } from "./Bitrix24IntegrationWhereUniqueInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";
import { Bitrix24IntegrationUpdateInput } from "./Bitrix24IntegrationUpdateInput";

@ArgsType()
class UpdateBitrix24IntegrationArgs {
  @ApiProperty({
    required: true,
    type: () => Bitrix24IntegrationWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => Bitrix24IntegrationWhereUniqueInput)
  @Field(() => Bitrix24IntegrationWhereUniqueInput, { nullable: false })
  where!: Bitrix24IntegrationWhereUniqueInput;

  @ApiProperty({
    required: true,
    type: () => Bitrix24IntegrationUpdateInput,
  })
  @ValidateNested()
  @Type(() => Bitrix24IntegrationUpdateInput)
  @Field(() => Bitrix24IntegrationUpdateInput, { nullable: false })
  data!: Bitrix24IntegrationUpdateInput;
}

export { UpdateBitrix24IntegrationArgs as UpdateBitrix24IntegrationArgs };
